version: "2"

linters:
  default: standard
  exclusions:
    generated: strict
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path-except: "proxy[/\\\\]reflex"
        linters:
          - errcheck
          - staticcheck
          - govet
          - unused
          - ineffassign
